version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kinesis-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b194xt23xtea"
s3_prefix = "kinesis-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
